name:         Customfield basename modification SQL error bug patch
version:      1.0.0
description:  'This plugin patches a bug in the MT Commercial pack in which saving a custom field with an altered basename leads to a SQL error caught at line 614 of lib/MT/ObjectDriver/Driver/DBI.pm. This often occurs when Theme Manager is applying a new theme with custom fields.<br /><br />This plugin ONLY has an effect on the system if <code><strong>CFBasenameModPatchEnabled</strong></code> is set to the <strong>current MT version</strong> in <strong>mt-config.cgi</strong>.'
key:          CFBasenameModPatch
id:           CFBasenameModPatch
author_name:  "Jay Allen, Endevver LLC"
author_url:   http://endevver.com/

callbacks:
    post_init: $CFBasenameModPatch::CFBasenameModPatch::post_init

config_settings:
    CFBasenameModPatchEnabled:
        default: 0
